---
- name: Setting Resource Group Location to West Europe
  set_fact: resource_group_location=westeurope
  when: ahit_location_id == "WeEu"

- name: Setting Resource Group Location to West Europe
  set_fact: resource_group_location=northeurope
  when: ahit_location_id == "NoEu"

- name: Create Azure Resource Group
  azure_rm_resourcegroup:
    name: "{{ resource_group_name }}"
    location: "{{ resource_group_location }}"
    # tags:
    #   BusinessUnitName: "{{ tag_business_unit_name }}"
    #   ApplicationName: "{{ tag_application_name }}"
    #   ApplicationId: "{{ tag_application_id }}"
    #   EnvironmentId: "{{ tag_environment_id }}"
    #   Owner: "{{ tag_owner }}"
...