- name: Create Network Interface Card
  azure_rm_networkinterface:
    profile: '{{ subscription_profile_name }}'
    resource_group: "{{ resource_group_name }}"
    name: "{{ network_interface_name }}"
    virtual_network: "{{ virtual_network_name }}"
    subnet: "{{ virtual_subnet_name }}"
    public_ip_name: "{{ public_ip_address_name }}"
    security_group: "{{ network_security_group_name }}"
    tags:
      BusinessUnitName: "{{ tag_business_unit_name }}"
      ApplicationName: "{{ tag_application_name }}"
      ApplicationId: "{{ tag_application_id }}"
      EnvironmentId: "{{ tag_environment_id }}"
      Owner: "{{ tag_owner }}"