---
- name: Create Virtual Machine
  azure_rm_virtualmachine:
    profile: '{{ subscription_profile_name }}'
    resource_group: "{{ resource_group_name }}"
    name: "{{ vm_name }}"
    vm_size: "{{ vm_size }}"
    managed_disk_type: "{{ vm_managed_disk_type }}"
    #data_disks: "{{ vm_data_disks }}"
    admin_username: "{{ vm_admin_username }}"
    admin_password: "{{ vm_admin_password }}"
    network_interfaces: "{{ network_interface_name }}"
    ssh_public_keys:
      - path: "/home/{{ vm_admin_username }}/.ssh/authorized_keys"
        key_data: "{{ vm_ssh_public_key }}"
    image:
      offer: "{{ vm_offer }}"
      publisher: "{{ vm_publisher }}"
      sku: "{{ vm_sku }}"
      version: "{{ vm_sku_version }}"
    tags:
      BusinessUnitName: "{{ tag_business_unit_name }}"
      ApplicationName: "{{ tag_application_name }}"
      ApplicationId: "{{ tag_application_id }}"
      EnvironmentId: "{{ tag_environment_id }}"
      Owner: "{{ tag_owner }}"
  register: azure_rm_virtualmachine

- set_fact:
    azure_vm_ip_address: "{{ azure_rm_virtualmachine.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress }}"
    networkinterface_name: "{{ azure_rm_virtualmachine.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].name }}"

- name: Add VM Into Control Host Memory
  add_host:
    name: "{{ azure_vm_ip_address }}"
    groups: azure
    ansible_user: "{{ vm_admin_username }}"
    ansible_password: "{{ vm_admin_password }}"
    ansible_host_key_checking: false

- name: Wait For The SSH Port To Come Online
  wait_for:
    port: 22
    host: "{{ azure_vm_ip_address }}"
    timeout: 120

- name: Ensure the group azure exists in the dynamic inventory file
  lineinfile:
    state: present
    dest: test
    line: '[test]'

- name: Populate the dynamic inventory
  lineinfile:
    state: present
    dest: test
    insertafter: '\[test\]'
    regexp: "^{{ azure_vm_ip_address }}.*"
    line: "{{ azure_vm_ip_address }} ansible_user=root"
...