---  
  - name: Create Virtual Network
    azure_rm_virtualnetwork:
      profile: "{{ subscription_profile_name }}"
      resource_group: "{{ resource_group_name }}"
      name: "{{ virtual_network_name }}"
      address_prefixes: "{{ virtual_network_address_prefix }}"
      tags:
        BusinessUnitName: "{{ tag_business_unit_name }}"
        ApplicationName: "{{ tag_application_name }}"
        ApplicationId: "{{ tag_application_id }}"
        EnvironmentId: "{{ tag_environment_id }}"
        Owner: "{{ tag_owner }}"
...